trigger:
  - master
  - azure-pipelines

pool:
    vmImage: 'windows-latest'
steps:
    - script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs/x86_64
        rustup-init.exe -y --default-toolchain stable
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo '##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin'
        rustup update
        rustc -V
        cargo -V
      displayName: install rust

    - script: |
        cargo test
      displayName: test dxplr
      continueOnError: true

    - script: |
        cargo test --features="dxgi1_2"
      displayName: test dxplr dxgi1_2
      continueOnError: true

    - script: |
        cargo test --features="dxgi1_3"
      displayName: test dxplr dxgi1_3
      continueOnError: true

    - script: |
        cargo test --features="dxgi1_4"
      displayName: test dxplr dxgi1_4
      continueOnError: true

    - script: |
        cargo test --features="dxgi1_5"
      displayName: test dxplr dxgi1_5
      continueOnError: true

    - script: |
        cargo test --features="dxgi1_6"
      displayName: test dxplr dxgi1_6
      continueOnError: true

    - script: |
        cargo test --features="d3d11_1"
      displayName: test dxplr d3d11_1
      continueOnError: true

    - script: |
        cargo test --features="d3d11_2"
      displayName: test dxplr d3d11_2
      continueOnError: true

    - script: |
        cargo test --features="d3d11_3"
      displayName: test dxplr d3d11_3
      continueOnError: true

    - script: |
        cargo test --features="d3d11_4"
      displayName: test dxplr d3d11_4
      continueOnError: true

    - script: |
        cargo test --features="d3dcompiler"
      displayName: test dxplr d3dcompiler
      continueOnError: true
