trigger:
  - master
  - azure-pipelines

pool:
    vmImage: 'windows-latest'
steps:
    - script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs/x86_64
        rustup-init.exe -y --default-toolchain stable
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo '##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin'
        rustup update
        rustc -V
        cargo -V
      displayName: install rust
    - script: |
        cargo install cargo2junit
      displayName: install cargo2junit

    - script: |
        cargo test -- -Z unstable-options --format json > result.json
      displayName: test dxplr
    - script: |
        cargo2junit result.json > result.xml
      displayName: cargo2junit
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'result.xml'
      condition: succeededOrFailed()

    - script: |
        cargo test --features="dxgi1_2" -- -Z unstable-options --format json > result.json
      displayName: test dxplr dxgi1_2
    - script: |
        cargo2junit result.json > result.xml
      displayName: cargo2junit
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'result.xml'
      condition: succeededOrFailed()

    - script: |
        cargo test --features="dxgi1_3" -- -Z unstable-options --format json > result.json
      displayName: test dxplr dxgi1_3
    - script: |
        cargo2junit result.json > result.xml
      displayName: cargo2junit
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'result.xml'
      condition: succeededOrFailed()

    - script: |
        cargo test --features="dxgi1_4" -- -Z unstable-options --format json > result.json
      displayName: test dxplr dxgi1_4
    - script: |
        cargo2junit result.json > result.xml
      displayName: cargo2junit
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'result.xml'
      condition: succeededOrFailed()
      continueOnError: true

    - script: |
        cargo test --features="dxgi1_5" -- -Z unstable-options --format json > result.json
      displayName: test dxplr dxgi1_5
    - script: |
        cargo2junit result.json > result.xml
      displayName: cargo2junit
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'result.xml'
      condition: succeededOrFailed()

    - script: |
        cargo test --features="dxgi1_6" -- -Z unstable-options --format json > result.json
      displayName: test dxplr dxgi1_6
    - script: |
        cargo2junit result.json > result.xml
      displayName: cargo2junit
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'result.xml'
      condition: succeededOrFailed()

    - script: |
        cargo test --features="d3d11_1" -- -Z unstable-options --format json > result.json
      displayName: test dxplr d3d11_1
    - script: |
        cargo2junit result.json > result.xml
      displayName: cargo2junit
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'result.xml'
      condition: succeededOrFailed()
      continueOnError: true

    - script: |
        cargo test --features="d3d11_2" -- -Z unstable-options --format json > result.json
      displayName: test dxplr d3d11_2
    - script: |
        cargo2junit result.json > result.xml
      displayName: cargo2junit
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'result.xml'
      condition: succeededOrFailed()

    - script: |
        cargo test --features="d3d11_3" -- -Z unstable-options --format json > result.json
      displayName: test dxplr d3d11_3
    - script: |
        cargo2junit result.json > result.xml
      displayName: cargo2junit
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'result.xml'
      condition: succeededOrFailed()

    - script: |
        cargo test --features="d3d11_4" -- -Z unstable-options --format json > result.json
      displayName: test dxplr d3d11_4
    - script: |
        cargo2junit result.json > result.xml
      displayName: cargo2junit
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'result.xml'
      condition: succeededOrFailed()

    - script: |
        cargo test --features="d3dcompiler" -- -Z unstable-options --format json > result.json
      displayName: test dxplr d3dcompiler
    - script: |
        cargo2junit result.json > result.xml
      displayName: cargo2junit
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'result.xml'
      condition: succeededOrFailed()
