trigger:
  - master
  - azure-pipelines

pool:
    vmImage: 'windows-latest'
steps:
    - script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs/x86_64
        rustup-init.exe -y --default-toolchain stable
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo '##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin'
        rustup update
        rustc -V
        cargo -V
      displayName: install rust

    - script: |
        cargo test
      displayName: test dxplr
      continueOnError: true

    - script: |
        cargo test --features="dxgi"
      displayName: test dxplr dxgi
      continueOnError: true

    - script: |
        cargo test --features="dxgi1_2"
      displayName: test dxplr dxgi1_2
      continueOnError: true

    - script: |
        cargo test --features="dxgi1_3"
      displayName: test dxplr dxgi1_3
      continueOnError: true

    - script: |
        cargo test --features="dxgi1_4"
      displayName: test dxplr dxgi1_4
      continueOnError: true

    - script: |
        cargo test --features="dxgi1_5"
      displayName: test dxplr dxgi1_5
      continueOnError: true

    - script: |
        cargo test --features="dxgi1_6"
      displayName: test dxplr dxgi1_6
      continueOnError: true

    - script: |
        cargo test --features="dxgidebug"
      displayName: test dxplr dxgidebug
      continueOnError: true

    - script: |
        cargo test --features="d3d11"
      displayName: test dxplr d3d11
      continueOnError: true

    - script: |
        cargo test --features="d3d11_1"
      displayName: test dxplr d3d11_1
      continueOnError: true

    - script: |
        cargo test --features="d3d11_2"
      displayName: test dxplr d3d11_2
      continueOnError: true

    - script: |
        cargo test --features="d3d11_3"
      displayName: test dxplr d3d11_3
      continueOnError: true

    - script: |
        cargo test --features="d3d11_4"
      displayName: test dxplr d3d11_4
      continueOnError: true

    - script: |
        cargo test --features="d3d11sdklayers"
      displayName: test dxplr d3d11sdklayers
      continueOnError: true

    - script: |
        cargo test --features="d3d12"
      displayName: test dxplr d3d12
      continueOnError: true

    - script: |
        cargo test --features="d3d12sdklayers"
      displayName: test dxplr d3d12sdklayers
      continueOnError: true

    - script: |
        cargo test --features="d3dcompiler"
      displayName: test dxplr d3dcompiler
      continueOnError: true

    - script: |
        cargo test --features="d3d11on12"
      displayName: test dxplr d3d11on12
      continueOnError: true

    - script: |
        cargo test --features="d2d1"
      displayName: test dxplr d2d1
      continueOnError: true

    - script: |
        cargo test --features="d2d1_1"
      displayName: test dxplr d2d1_1
      continueOnError: true

    - script: |
        cargo test --features="d2d1_2"
      displayName: test dxplr d2d1_2
      continueOnError: true

    - script: |
        cargo test --features="d2d1_3"
      displayName: test dxplr d2d1_3
      continueOnError: true

    - script: |
        cargo test --features="dwrite"
      displayName: test dxplr dwrite
      continueOnError: true

    - script: |
        cargo test --features="dwrite_1"
      displayName: test dxplr dwrite_1
      continueOnError: true

    - script: |
        cargo test --features="dwrite_2"
      displayName: test dxplr dwrite_2
      continueOnError: true

    - script: |
        cargo test --features="dwrite_3"
      displayName: test dxplr dwrite_3
      continueOnError: true

    - script: |
        cargo test --features="d2d1,dwrite"
      displayName: test dxplr d2d1 dwrite
      continueOnError: true
